### ISSUE TITLE
JSHint is running twice

### ISSUE THREAD

**Issue by cktech529** [RallyApps/rally-app-builder#58] opened 2016-07-07 21:46 UTC
JSHINT for Rallly App Builder looks like it is running twice... This is after creating a new app using init...

rally-app-builder build
Compiling the App.
Error in ucomp/ObjContainer.js on line 300: ['Accepted'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 302: ['Completed'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 306: ['Defined'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 308: ['Missed'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 320: ['Missed'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 701: Don't make functions within a loop.
Error in ucomp/ObjContainer.js on line 706: Don't make functions within a loop.
Error in ucomp/OthContainer.js on line 80: ['Accepted'] is better written in dot notation.
Error in ucomp/OthContainer.js on line 82: ['Completed'] is better written in dot notation.
Error in ucomp/OthContainer.js on line 85: ['Defined'] is better written in dot notation.
Error in ucomp/OthContainer.js on line 87: ['Missed'] is better written in dot notation.
Error in ucomp/OthContainer.js on line 99: ['Missed'] is better written in dot notation.
Error in ucomp/SummaryContainer.js on line 507: Don't make functions within a loop.
Error in ucomp/DependencyContainer.js on line 513: Don't make functions within a loop.
Error in ucomp/DependencyContainer.js on line 518: Don't make functions within a loop.
Error in rmodel/DataLoader.js on line 1028: ['EPIC'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1031: ['STRETCH'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1034: ['ARCH'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1037: ['REFA'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1040: ['INNOV'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1043: ['PROG'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1046: ['SPIKE'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1049: ['PRODUCER'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1052: ['CONSUMER'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1055: ['DEPENDENCY'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1060: ['EPIC'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1420: ['FoundParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1422: ['FoundParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1425: ['FoundExtParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1427: ['FoundExtParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1429: ['FoundExtParentPSI'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1434: ['FoundParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1436: ['FoundExtParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1438: ['FoundExtParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1440: ['FoundExtParentPSI'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1445: ['FoundParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1447: ['FoundParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1449: ['FoundParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1503: ['FoundParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1601: ['Objective'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1803: Don't make functions within a loop.
Error in rmodel/DataLoader.js on line 2182: ['EPIC'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2184: ['STRETCH'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2186: ['ARCH'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2188: ['REFA'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2190: ['INNOV'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2192: ['PROG'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2194: ['SPIKE'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2196: ['PRODUCER'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2198: ['CONSUMER'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2200: ['DEPENDENCY'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 300: ['Accepted'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 302: ['Completed'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 306: ['Defined'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 308: ['Missed'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 320: ['Missed'] is better written in dot notation.
Error in ucomp/ObjContainer.js on line 701: Don't make functions within a loop.
Error in ucomp/ObjContainer.js on line 706: Don't make functions within a loop.
Error in ucomp/OthContainer.js on line 80: ['Accepted'] is better written in dot notation.
Error in ucomp/OthContainer.js on line 82: ['Completed'] is better written in dot notation.
Error in ucomp/OthContainer.js on line 85: ['Defined'] is better written in dot notation.
Error in ucomp/OthContainer.js on line 87: ['Missed'] is better written in dot notation.
Error in ucomp/OthContainer.js on line 99: ['Missed'] is better written in dot notation.
Error in ucomp/SummaryContainer.js on line 507: Don't make functions within a loop.
Error in ucomp/DependencyContainer.js on line 513: Don't make functions within a loop.
Error in ucomp/DependencyContainer.js on line 518: Don't make functions within a loop.
Error in rmodel/DataLoader.js on line 1028: ['EPIC'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1031: ['STRETCH'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1034: ['ARCH'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1037: ['REFA'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1040: ['INNOV'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1043: ['PROG'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1046: ['SPIKE'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1049: ['PRODUCER'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1052: ['CONSUMER'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1055: ['DEPENDENCY'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1060: ['EPIC'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1420: ['FoundParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1422: ['FoundParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1425: ['FoundExtParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1427: ['FoundExtParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1429: ['FoundExtParentPSI'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1434: ['FoundParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1436: ['FoundExtParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1438: ['FoundExtParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1440: ['FoundExtParentPSI'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1445: ['FoundParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1447: ['FoundParent'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1449: ['FoundParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1503: ['FoundParentID'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1601: ['Objective'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 1803: Don't make functions within a loop.
Error in rmodel/DataLoader.js on line 2182: ['EPIC'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2184: ['STRETCH'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2186: ['ARCH'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2188: ['REFA'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2190: ['INNOV'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2192: ['PROG'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2194: ['SPIKE'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2196: ['PRODUCER'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2198: ['CONSUMER'] is better written in dot notation.
Error in rmodel/DataLoader.js on line 2200: ['DEPENDENCY'] is better written in dot notation.
Creating App-debug.html
Creating App.html
Creating App-external.html
Creating App-uncompressed.html
Success
usxxkingc5m4:TestApp kingc5$ 

When I run grunt - it doesn't throw any JSHint errors and ignores what I tell it to ignore in the options below:

// The grunt file.
var module = module;
//this keeps the module file from doing anything inside the jasmine tests.
//We could avoid this by making all the source be in a specific directory, but that would break backwards compatibility.
if (module) {
    module.exports = function (grunt) {
        'use strict';

        var config, debug, environment, spec;
        grunt.loadNpmTasks('grunt-contrib-jasmine');
        grunt.loadNpmTasks('grunt-contrib-jshint');

        grunt.registerTask('test', ['jshint','jasmine']);
        grunt.registerTask('default', ['test']);

        spec = grunt.option('spec') || '*';
        config = grunt.file.readJSON('config.json');
        return grunt.initConfig({

            pkg: grunt.file.readJSON('package.json'),

            jasmine: {
                dev: {
                    src: "./*.js",
                    options: {
                        vendor:["https://rally1.rallydev.com/apps/"+config.sdk+"/sdk-debug.js"],
                        template: 'test/specs.tmpl',
                        specs: "test/**/" + spec + "Spec.js",
                        helpers: []
                    }
                }
            },
            jshint:{
                options: {
                    bitwise: true,
                    curly: true,
                    eqeqeq: true,
                    forin: true,
                    immed: true,
                    latedef: true,
                    noarg: true,
                    noempty: true,
                    nonew: true,
                    trailing: true,
                    browser: true,
                    unused: 'vars',
                    es3: true,
                    laxbreak: true,
                    '-W069': true,
                    '-W083': true
                },
                apps: {
                    files: {
                        src: [
                            'store/**/*.js',
                            'overrides/**/*.js',
                            'rmodel/**/*.js',
                            'test/**/*.js',
                            'ucomp/**/*.js'
                        ]
                    }
                }
            }
        });
  }
}

When I run grunt or npm test, I get

usxxkingc5m4:ObjectivesDashboard kingc5$ grunt
Running "jshint:apps" (jshint) task
>> 11 files lint free.

Running "jasmine:dev" (jasmine) task
Testing jasmine specs via phantom
.
1 spec in 0.002s.
>> 0 failures

Done, without errors.
usxxkingc5m4:ObjectivesDashboard kingc5$ 

> MyApp@0.1.1 test /c4_working/TestApp
> grunt

Running "jshint:apps" (jshint) task
>> 11 files lint free.

Running "jasmine:dev" (jasmine) task
Testing jasmine specs via phantom
.
1 spec in 0.001s.
>> 0 failures

Done, without errors.
usxxkingc5m4:TestApp kingc5$

**Comment by krmorse** [comment] 2016-07-11 20:37
I was definitely able to reproduce the behavior you describe here with it running twice.  I just submitted a pull request to fix that and to also add a .jshintrc file to your app so you can control the options.

https://github.com/RallyApps/rally-app-builder/pull/59

**Comment by krmorse** [comment] 2016-07-11 20:39
The whole gruntfile thing is weird because the only thing it is really used for is the tests...

**Comment by krmorse** [comment] 2016-07-12 01:50
Fixed in version 1.2.9.  You can also now add a .jshintrc file in your app root directory to configure what options you'd like.  The default is here: https://raw.githubusercontent.com/RallyApps/rally-app-builder/master/templates/.jshintrc

**Closed by krmorse** 2016-07-12 01:50 UTC

**Comment by cktech529** [comment] 2016-09-13 13:32
Thanks! For some reason I had missed all of your updates on this. I appreciate and have been using the fix.
